* Fully Implicit Black Oil Simulator
[2017-01-21 Sa 13:33]

** Black oil equations
[2017-01-26 Do 14:13]
\begin{equation}
\frac{\partial}{\partial t} \left[ \phi \left( \frac{s_o}{B_o} + \frac{r_v
s_g}{B_g}\right)\right] + \nabla \cdot \left(\frac{1}{B_o} {\mathbf
{\mathbf v}}_o + \frac{r_v}{B_g}
v_g \right)= q_o + r_v q_g
\end{equation}
\begin{equation}
\frac{\partial}{\partial t} \left[\phi \left(\frac{r_s s_o}{B_o} +
\frac{s_g}{B_g} \right) \right] + \nabla \left( \frac{r_s}{B_o}
{\mathbf v}_o + \frac{1}{B_g} {\mathbf v}_g\right) = r_s q_o + q_g
\end{equation}
\begin{equation}
\frac{\partial}{\partial t} \left[ \phi  \frac{s_w}{B_w}
\right] + \nabla \cdot \left( \frac{1}{B_w} {\mathbf v}_w \right) = q_w\,,
\end{equation}
where \(s_o, s_g, s_w\) are the oil, gas and water saturation satisfying
\begin{equation}
s_o + s_g + s_w = 1\,.
\end{equation}
\({\mathbf v}_\alpha\) with $\alpha \in \{o, g, w\}$ are the well known Darcy velocities defined by
\begin{equation}
{\mathbf v}_\alpha = - \frac{k_{r,\alpha}}{\mu_\alpha} K \left(\nabla p_\alpha - \rho_\alpha {\mathbf g} \right) \quad \alpha \in
\{o, g, w\}
\end{equation}
dependant on the phase pressure $p_\alpha$, the absolute permeability tensor
$K$, the viscosity $\mu_\alpha$ of phase $\alpha$,  and
the phase density $\rho_\alpha$. $B_\alpha$ is the volume formation factor of
phase $\alpha$, $r_s$ is the solution gas-oil ratio, $r_v$ the
vaporized oil ratio, $q_\alpha$ the well term of phase $\alpha$ and $\phi$ the porosity,
$k_{r,\alpha}$ is the relative permeability of the phase $\alpha$.

** Well Models
[2017-01-26 Do 14:13]

The simulator supports two well models: a standard one that we will
describe here and  a multisegment well mode as described in
cite:holmes1998application. 

TODO describe equations.

** Hard Numerical Problem
[2017-01-26 Do 14:14]

+ Properties dependant on saturation and pressure.
+ Highly nonlinear
+ Highly coupled
+ Complicated geometry (faults, irregular domains)
+ Permeability jumps.

** Discretization and Solver
[2017-01-26 Do 14:22]

+ Cornerpoint Grid
+ Cell centered finite volums with upwinding
+ Two point flux approximation
+ Fully implicit formulation
+ CPR with AMG / Block ILU0

The simulator can read and write to and from files formatted for the
commercial reservoir simulator Eclipse. This makes
switching to OPM as easy as possible as the file
format is a de facto industry standard.

** Input / output
[2017-01-26 Do 14:25]

The simulator can read and write to formatted for the commericial oil
reservoir simulator Eclipse.
